"""create tables

Revision ID: 27c86c48abb8
Revises: 
Create Date: 2026-06-15 16:52:53.549547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c86c48abb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clid', sa.String(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('click_spend', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clid')
    )
    op.create_index(op.f('ix_clicks_clid'), 'clicks', ['clid'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clid', sa.String(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clid', 'ts', name='unique_clid_ts')
    )
    op.create_index(op.f('ix_payments_clid'), 'payments', ['clid'], unique=False)
    op.create_table('advantage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='eventstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advantage_events')
    op.drop_index(op.f('ix_payments_clid'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_clicks_clid'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###
